#!/usr/bin/env python3
"""Regenerate the derived terminology copy in this repo from the master dictionary.

`content/glossary/terminology.yml` is a copy. The master lives in the shared
sdd-workflow repo and is the only place terms are edited. This script pulls the
master across and stamps today's date on the derived file's header.

It drifted once already: by August 2026 the copy held 37 terms against the
master's 55, had lost most translations, and had picked up edits of its own that
existed nowhere else. Run this after every dictionary change so that cannot
happen again quietly.

    python3 scripts/sync_terminology.py            # write the copy
    python3 scripts/sync_terminology.py --check    # report drift, write nothing
"""
import argparse
import datetime
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip3 install pyyaml")

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DEFAULT_MASTER = os.path.abspath(
    os.path.join(REPO, "..", "sdd-workflow", "translations", "terminology.yml")
)
DERIVED = os.path.join(REPO, "content", "glossary", "terminology.yml")

# Everything from here down is carried over verbatim; the master's own banner is
# replaced, because a copy must not claim to be the master.
BODY_MARKER = "# Fields per term:"

ap = argparse.ArgumentParser()
ap.add_argument("--master", default=DEFAULT_MASTER)
ap.add_argument("--out", default=DERIVED)
ap.add_argument("--check", action="store_true", help="report drift and exit non-zero")
args = ap.parse_args()

if not os.path.exists(args.master):
    sys.exit(f"Master dictionary not found: {args.master}")

with open(args.master, encoding="utf-8") as f:
    master_text = f.read()

if BODY_MARKER not in master_text:
    sys.exit(f"Could not find '{BODY_MARKER}' in the master — has its header changed?")

body = master_text[master_text.index(BODY_MARKER):]
today = datetime.date.today().isoformat()

header = f"""# Zooza Terminology Dictionary — DERIVED COPY
#
# ╔══════════════════════════════════════════════════════════════════╗
# ║  DO NOT EDIT THIS FILE DIRECTLY.                                ║
# ║  Master is: sdd-workflow/translations/terminology.yml           ║
# ║  Edit there, then run: python3 scripts/sync_terminology.py      ║
# ╚══════════════════════════════════════════════════════════════════╝
#
# Last synced: {today}
# Used by: scripts/normalize_terminology.py → build/terminology/dictionary.json
#
"""

new_text = header + body

master = yaml.safe_load(master_text)
generated = yaml.safe_load(new_text)
assert [t["id"] for t in generated["terms"]] == [t["id"] for t in master["terms"]], \
    "generated copy does not match the master term list"

existing = ""
if os.path.exists(args.out):
    with open(args.out, encoding="utf-8") as f:
        existing = f.read()

if args.check:
    try:
        cur = yaml.safe_load(existing) if existing else {"terms": []}
    except yaml.YAMLError:
        cur = {"terms": []}
    cur_ids = {t["id"] for t in cur.get("terms", [])}
    mas_ids = {t["id"] for t in master.get("terms", [])}
    missing = sorted(mas_ids - cur_ids)
    orphan = sorted(cur_ids - mas_ids)
    if missing or orphan:
        print(f"Derived copy is behind the master ({len(cur_ids)} vs {len(mas_ids)} terms).")
        if missing:
            print("  missing from the copy:", ", ".join(missing))
        if orphan:
            print("  in the copy but not the master:", ", ".join(orphan))
            print("  → merge these into the master first; syncing would drop them.")
        print("\nRun: python3 scripts/sync_terminology.py")
        sys.exit(1)
    print(f"Derived copy is in sync ({len(cur_ids)} terms).")
    sys.exit(0)

with open(args.out, "w", encoding="utf-8") as f:
    f.write(new_text)

print(f"Synced {len(master['terms'])} terms → {os.path.relpath(args.out, REPO)}")
print(f"  public terms: {sum(1 for t in master['terms'] if t.get('public'))}")
